### PR TITLE
Es2018

### LINKED ISSUE #14: Lint doesn't allow cloning via Object.assign({}, obj) or via { ...obj }
As noted [here](https://github.com/peggyjs/peggy/pull/425#discussion_r1307692020), `Object.assign({}, obj)` tells you to use `{ ...obj }`, but `{ ...obj }` reports a parser error.

I verified that updating parserOptions.ecmaVersion to 2018 fixes the parser error, and that uses of `{ ...obj }` get converted to `__assign({}, obj)`, where __assign is a wrapper around Object.assign, or a stub if that doesn't exist.

### PR DESCRIPTION
**Pull request by hildjj**
Fixes #14

### CODE REVIEW

**Comment by hildjj** [comment]
@markw65 please look

**Comment by markw65** [comment]
Looks good to me - but I'm not sure how to actually test this change against peggy...

**Comment by hildjj** [comment]
Eh, we'll just land it and publish a version, then you can update the version in your branch and do an `npm install`.  If it doesn't work, we'll do another version quickly here.

I assume I'm the only one using this on non-peggy projects, so I'm not worried about side-effects.

**Comment by hildjj** [comment]
@markw65 ready for you to give it a shot.

**Comment by markw65** [comment]
Yes, it works for me. I changed this [clone](https://github.com/peggyjs/peggy/blob/4ce553016a274e1e9ef626e92e5953c5eb4e69c0/test/behavior/generated-parser-behavior.spec.js#L9-L16) method to return `{ ...object }`, and lint was happy, and the tests passed.

Also, `npm run lint` and `npm run ts` report no errors (changing the versions might have caused an issue).

**Comment by markw65** [comment]
Should I put up a pull request to pull this into peggy? Or I could add it to eg https://github.com/peggyjs/peggy/pull/425 and update the pull request to use it?

**Comment by hildjj** [comment]
Yeah, just add it to 425.  If you could update all dependencies in one commit (including the updated lock file after doing an `npm install`), that would be best.

**Pull request merged**
